CREATE TABLE IF NOT EXISTS product
(
    product_id   bigint generated by default as identity,
    desc         varchar(255),
    product_name varchar(255),
    price        bigint,
    product_type varchar(50),
    primary key (product_id)
    );
CREATE TABLE IF NOT EXISTS promotion
(
    promotion_id    bigint generated by default as identity,
    end_date_time   timestamp,
    start_date_time timestamp,
    product_id      bigint,
    promotion_type  varchar(50),
    value           bigint,
    primary key (promotion_id),
    FOREIGN KEY (product_id)
    REFERENCES Product(product_id)
    );
CREATE TABLE IF NOT EXISTS user
(
    user_id    bigint generated by default as identity,
    user_name  varchar(255),
    user_state varchar(50),
    user_type  varchar(50),
    primary key (user_id)
    );